# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/any_notebook_name.ipynb.

# %% auto 0
__all__ = ['say_hello', 'foo']

# %% ../nbs/any_notebook_name.ipynb 2
def say_hello(to):
    "Say hello to somebody"
    return f'Hello {to}!'

# %% ../nbs/any_notebook_name.ipynb 8
def foo(): pass
